name: flutter_keyboard_visibility_web
publish_to: none
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 2.0.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPluginWeb
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: 
    git: https://github.com/kumsumit/flutter_keyboard_visibility_platform_interface.git
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  flutter_test:
    sdk: flutter